MLB_M3U8_MAP = {
    'LAA': 'https://dlhd.net/MLBTVLAA/B0001/1.m3u8',
    'BAL': 'https://dlhd.net/MLBTVBAL/B0004/1.m3u8',
    'BOS': 'https://dlhd.net/MLBTVBOS/B0005/1.m3u8',
    'CWS': 'https://dlhd.net/MLBTVCHW/B0007/1.m3u8',
    'CLE': 'https://dlhd.net/MLBTVCLE/B0009/1.m3u8',
    'DET': 'https://dlhd.net/MLBTVDET/B0011/1.m3u8',
    'HOU': 'https://dlhd.net/MLBTVHOU/B0013/1.m3u8',
    'KC':  'https://dlhd.net/MLBTVKCR/B0014/1.m3u8',
    'MIN': 'https://dlhd.net/MLBTVMIN/B0017/1.m3u8',
    'NYY': 'https://dlhd.net/MLBTVNYY/B0020/1.m3u8',
    'ATH': 'https://dlhd.net/MLBTVATH/B0021/1.m3u8',
    'SEA': 'https://dlhd.net/MLBTVSEA/B0026/1.m3u8',
    'TB':  'https://dlhd.net/MLBTVTBR/B0028/1.m3u8',
    'TEX': 'https://dlhd.net/MLBTVTEX/B0029/1.m3u8',
    'TOR': 'https://dlhd.net/MLBTVTOR/B0030/1.m3u8',
    'AZ':  'https://dlhd.net/MLBTVARI/B0002/1.m3u8',
    'ATL': 'https://dlhd.net/MLBTVATL/B0003/1.m3u8',
    'CHC': 'https://dlhd.net/MLBTVCHC/B0006/1.m3u8',
    'CIN': 'https://dlhd.net/MLBTVCIN/B0008/1.m3u8',
    'COL': 'https://dlhd.net/MLBTVCOL/B0010/1.m3u8',
    'LAD': 'https://dlhd.net/MLBTVLAD/B0015/1.m3u8',
    'MIA': 'https://dlhd.net/MLBTVMIA/B0012/1.m3u8',
    'MIL': 'https://dlhd.net/MLBTVMIL/B0016/1.m3u8',
    'NYM': 'https://dlhd.net/MLBTVNYM/B0019/1.m3u8',
    'PHI': 'https://dlhd.net/MLBTVPHI/B0022/1.m3u8',
    'PIT': 'https://dlhd.net/MLBTVPIT/B0023/1.m3u8',
    'SD':  'https://dlhd.net/MLBTVSDP/B0024/1.m3u8',
    'SF':  'https://dlhd.net/MLBTVSFG/B0025/1.m3u8',
    'STL': 'https://dlhd.net/MLBTVSTL/B0027/1.m3u8',
    'WSH': 'https://dlhd.net/MLBTVWAS/B0018/1.m3u8',
    'WAS': 'https://dlhd.net/MLBTVWAS/B0018/1.m3u8',
}

WNBA_M3U8_MAP = {
    'ATL': 'https://247v2.dlhd.net/?stream_id=atlantadream&pro_id=sling&index.m3u8',
    'CHI': 'https://247v2.dlhd.net/?stream_id=chicagosky&pro_id=sling&index.m3u8',
    'CON': 'https://247v2.dlhd.net/?stream_id=connecticutsun&pro_id=sling&index.m3u8',
    'DAL': 'https://247v2.dlhd.net/?stream_id=dallaswings&pro_id=sling&index.m3u8',
    'GSV': 'https://247v2.dlhd.net/?stream_id=goldenstatevalkyries&pro_id=sling&index.m3u8',
    'IND': 'https://247v2.dlhd.net/?stream_id=indianafever&pro_id=sling&index.m3u8',
    'LVA': 'https://247v2.dlhd.net/?stream_id=lasvegasaces&pro_id=sling&index.m3u8',
    'LAS': 'https://247v2.dlhd.net/?stream_id=losangelessparks&pro_id=sling&index.m3u8',
    'MIN': 'https://247v2.dlhd.net/?stream_id=minnesotalynx&pro_id=sling&index.m3u8',
    'NYL': 'https://247v2.dlhd.net/?stream_id=newyorkliberty&pro_id=sling&index.m3u8',
    'PHO': 'https://247v2.dlhd.net/?stream_id=phoenixmercury&pro_id=sling&index.m3u8',
    'PDX': 'https://247v2.dlhd.net/?stream_id=portlandfire&pro_id=sling&index.m3u8',
    'SEA': 'https://247v2.dlhd.net/?stream_id=seattlestorm&pro_id=sling&index.m3u8',
    'TOR': 'https://247v2.dlhd.net/?stream_id=torontotempo&pro_id=sling&index.m3u8',
    'WAS': 'https://247v2.dlhd.net/?stream_id=washingtonmystics&pro_id=sling&index.m3u8',
}

WNBA_NATIONAL_MAP = {
    'nba tv':    ('NBATV', 'nbatv'),
    'espn':      ('ESPN', 'espn'),
    'espn2':     ('ESPN2', 'espn2'),
    'nbc':       ('NBC', 'nbcwnbc'),
    'abc':       ('ABC', 'abcwabc'),
    'ion':       ('ION', 'ion'),
    'fox':       ('FOX', 'foxwnyw'),
    'cbs':       ('CBS', 'cbswnycbs'),
    'tnt':       ('TNT', 'tnt'),
    'tbs':       ('TBS', 'tbs'),
    'fs1':       ('FS1', 'foxsports1'),
    'fs2':       ('FS2', 'foxsports2'),
    'usa network': ('USA Network', 'usa'),
}

FUBO_NATIONAL_MAP = {
    'FOX':  'https://dlhd.net/KDKA/F0023/master.m3u8',
    'CBS':  'https://dlhd.net/KCBS/F0002/master.m3u8',
    'NBC':  'https://dlhd.net/WNBC/N1021/master.m3u8',
    'ABC':  'https://dlhd.net/WABC/F3029/master.m3u8',
}
